백엔드/Test_project/photo/urls.py
from django.urls import path
from .views import PhotoList, PhotoDelete, PhotoDetail, PhotoUpdate, PhotoCreate, PhotoLike1, PhotoLike2, PhotoLike3, PhotoLike4, PhotoLike5
from django.conf.urls.static import static
from django.conf import settings

app_name = "photo"
urlpatterns = [
    path('create/',PhotoCreate.as_view(), name='create'),
    path('delete/<int:pk>/',PhotoDelete.as_view(), name='delete'),
    path('update/<int:pk>/',PhotoUpdate.as_view(), name='update'),
    path('detail/<int:pk>/',PhotoDetail.as_view(), name='detail'),
    path('',PhotoList.as_view(), name='index'),
    path('like1/<int:photo_id>/',PhotoLike1.as_view(), name='like1'),
    path('like2/<int:photo_id>/',PhotoLike2.as_view(), name='like2'),
    path('like3/<int:photo_id>/',PhotoLike3.as_view(), name='like3'),
    path('like4/<int:photo_id>/',PhotoLike4.as_view(), name='like4'),
    path('like5/<int:photo_id>/',PhotoLike5.as_view(), name='like5'),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

백엔드/Test_project/test_project/urls.py
from django.contrib import admin
from django.urls import path, include
import photo.views

urlpatterns = [
    path('', include('photo.urls')),
    path('accounts/',include('accounts.urls')),
    path('admin/', admin.site.urls),
    path(r'^(?P<post_pk>\d+)/comment/new/$',photo.views.comment_new,name='comment_new'), 
    path(r'^(?P<post_pk>\d+)/comment/(?P<pk>\d+)/edit/$',photo.views.comment_edit,name='comment_edit'), 
    path(r'^(?P<post_pk>\d+)/comment/(?P<pk>\d+)/delete/$',photo.views.comment_delete,name='comment_delete'), 
]

백엔드/Test_project/photo/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse

from django.contrib.auth import get_user_model
from django.utils import timezone
from django import forms
from django.conf import settings
# Create your models here.

class Photo(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user')
    text = models.TextField(blank=True)
    image = models.ImageField(upload_to='timeline_photo/%Y/%m/%d')
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    like1 = models.ManyToManyField(User, related_name='like1_post', blank=True)
    like2 = models.ManyToManyField(User, related_name='like2_post', blank=True)
    like3 = models.ManyToManyField(User, related_name='like3_post', blank=True)
    like4 = models.ManyToManyField(User, related_name='like4_post', blank=True)
    like5 = models.ManyToManyField(User, related_name='like5_post', blank=True)

    def __str__(self):
        return "text : " + self.text

    class Meta:
        ordering = ['-created']

    def get_absolute_url(self):
        return reverse('photo:detail',args=(self.id))


class Comment(models.Model):
    photo = models.ForeignKey(Photo,on_delete=True, null=True)
    author = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=True, null=True)
    comment_date = models.DateTimeField(default=timezone.now)
    comment_text = models.TextField()
    
    class Meta:
        ordering = ['comment_date'] #id역순으로 정렬이에용
    
    def get_edit_url(self):
        return reverse('comment_edit', args=[self.photo.pk,  self.pk])

    def get_delete_url(self):
        return reverse('comment_delete', args=[self.photo.pk,  self.pk])

백엔드/Test_project/photo/forms.py
from django import forms
from .models import Comment

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['comment_text']

백엔드/Test_project/photo/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic.list import ListView
from django.views.generic.edit import UpdateView, CreateView, DeleteView
from django.views.generic.detail import DetailView
from django.http import HttpResponseRedirect
from django.contrib import messages
from django.views.generic.base import View
from django.http import HttpResponseForbidden
from urllib.parse import urlparse

from django.contrib.auth.decorators import login_required
from .models import Photo, Comment
from .forms import CommentForm
# Create your views here.

class PhotoList(ListView):
    model = Photo
    template_name_suffix = '_list'
    
class PhotoCreate(CreateView):
    model = Photo
    fields = ['text', 'image']
    template_name_suffix = '_create'
    success_url = '/'

    def form_valid(self, form):
        form.instance.author_id = self.request.user.author_id
        if form.is_valid():
            form.instance.save()
            return redirect('/')
        else:
            return self.render_to_response({'form':form})

class PhotoUpdate(UpdateView):
    model = Photo
    fields = ['author','text','image']
    template_name_suffix = '_update'
    success_url = '/'

    def dispatch(self, request, *args, **kwargs):
        object = self.get_object()
        if object.author != request.user:
            messages.warning(request, '수정할 권한이 없습니다.')
            return HttpResponseRedirect('/')
            # 삭제 페이지에서 권한이 없다! 라고 띄우거나
            # detail페이지로 들어가서 삭제에 실패했습니다. 라고 띄우거나
        else:
            return super(PhotoUpdate, self).dispatch(request, *args, **kwargs)

class PhotoDelete(DeleteView):
    model = Photo
    template_name_suffix = '_delete'
    success_url = '/'

    def dispatch(self, request, *args, **kwargs):
        object = self.get_object()
        if object.author != request.user:
            messages.warning(request, '삭제할 권한이 없습니다.')
            return HttpResponseRedirect('/')
        else:
            return super(PhotoDelete, self).dispatch(request, *args, **kwargs)

class PhotoDetail(DetailView):
    model = Photo
    template_name_suffix = '_detail'

class PhotoLike1(View):
    def get(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return HttpResponseForbidden()
        else:
            if 'photo_id' in kwargs:
                photo_id = kwargs['photo_id']
                photo = Photo.objects.get(pk=photo_id)
                user = request.user
                if user in photo.like1.all():
                    photo.like1.remove(user)
                else:
                    photo.like1.add(user)
            referer_url = request.META.get('HTTP_REFERER')
            path = urlparse(referer_url).path
            return HttpResponseRedirect(path)

class PhotoLike2(View):
    def get(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return HttpResponseForbidden()
        else:
            if 'photo_id' in kwargs:
                photo_id = kwargs['photo_id']
                photo = Photo.objects.get(pk=photo_id)
                user = request.user
                if user in photo.like2.all():
                    photo.like2.remove(user)
                else:
                    photo.like2.add(user)
            referer_url = request.META.get('HTTP_REFERER')
            path = urlparse(referer_url).path
            return HttpResponseRedirect(path)

class PhotoLike3(View):
    def get(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return HttpResponseForbidden()
        else:
            if 'photo_id' in kwargs:
                photo_id = kwargs['photo_id']
                photo = Photo.objects.get(pk=photo_id)
                user = request.user
                if user in photo.like3.all():
                    photo.like3.remove(user)
                else:
                    photo.like3.add(user)
            referer_url = request.META.get('HTTP_REFERER')
            path = urlparse(referer_url).path
            return HttpResponseRedirect(path)
            
class PhotoLike4(View):
    def get(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return HttpResponseForbidden()
        else:
            if 'photo_id' in kwargs:
                photo_id = kwargs['photo_id']
                photo = Photo.objects.get(pk=photo_id)
                user = request.user
                if user in photo.like4.all():
                    photo.like4.remove(user)
                else:
                    photo.like4.add(user)
            referer_url = request.META.get('HTTP_REFERER')
            path = urlparse(referer_url).path
            return HttpResponseRedirect(path)
            
class PhotoLike5(View):
    def get(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return HttpResponseForbidden()
        else:
            if 'photo_id' in kwargs:
                photo_id = kwargs['photo_id']
                photo = Photo.objects.get(pk=photo_id)
                user = request.user
                if user in photo.like5.all():
                    photo.like5.remove(user)
                else:
                    photo.like5.add(user)
            referer_url = request.META.get('HTTP_REFERER')
            path = urlparse(referer_url).path
            return HttpResponseRedirect(path)

def comment_detail(request, photo_id):
    comment_detail = get_object_or_404(Photo, pk=photo_id)
    comments = Comment.objects.filter(photo_id=photo_id)

    context = {
        'comment_detail' : comment_detail,
        'comments' : comments
    }

    return render(request, 'photo_detail.html', context)

def comment_new(request, post_pk):
    post = get_object_or_404(Photo, pk=post_pk)
    
    if request.method == 'POST':
        form = CommentForm(request.POST, request.FILES)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.photo = post
            comment.author = request.user
            comment.save()  
            return redirect('/detail/' + str(post_pk))
    else:
        form = CommentForm()
    return render(request,'comment_form.html',{'form':form})

def comment_edit(request, post_pk,pk):
    comment = get_object_or_404(Comment, pk=pk)
    
    if comment.author != request.user:
        return redirect('detail',post_pk)
    
    if request.method == 'POST':
        form = CommentForm(request.POST, request.FILES,instance=comment)
        if form.is_valid():
            comment = form.save()
            return redirect('photo:detail',comment.photo.pk)
    else:
        form = CommentForm(instance=comment)
    return render(request,'comment_form.html',{'form':form})

    
def comment_delete(request, post_pk,pk):
    comment = get_object_or_404(Comment, pk=pk)
    #작성자만 삭제가능
    if comment.author != request.user:
        return redirect('photo:detail',post_pk)

    if request.method == 'POST':
        comment.delete()
        return redirect('photo:detail',post_pk)

    return render(request,'comment_confirm_delete.html',{'comment':comment,})

백엔드/Test_project/photo/templates/photo/photo_create.html
{% extends 'base.html' %}
{% block content %}
<div>
    <div></div>
    <div>
        <div role="alert">
            모든 부분을 다 채워주세요!!
        </div>
        <form action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}

            {{form.as_p}}
            <input type="submit" value="Upload">
        </form>
    </div>
    <div></div>
    </div>
</div>
{% endblock %}

백엔드/Test_project/photo/templates/photo/photo_delete.html
{% extends 'base.html' %}
{% block content %}

<div role="alert">
    진짜로 {{object}}를 지우실 건가요?
</div>
<form action="" method="post">
    {% csrf_token %}
    <input type="submit" value="Delete OK">
</form>
{% endblock %}

백엔드/Test_project/photo/templates/photo/photo_detail.html
{% extends 'base.html' %}
{% block title %}
{% endblock %}

{% block content %}
<div>
    <div></div>
    <div>
        <div>
            <img src="{{object.image.url}}" alt="...">
            <div>
                <h5>{{ object.author }}</h5>
                <p>{{ object.text }}</p>
            </div>
            <ul>
                <li>
                    <a href="{% url 'photo:like1' object.id %}" class ="">좋아요1!</a>
                    {% if object.like1.all.count %}
                    <span>
                        {{object.like1.all.count}}
                    </span>
                    {% endif %}
                    <a href="{% url 'photo:like2' object.id %}" class="">좋아요2!</a>
                    {% if object.like2.all.count %}
                    <span>
                        {{object.like2.all.count}}
                    </span>
                    {% endif %}
                    <a href="{% url 'photo:like3' object.id %}" class="">좋아요3!</a>
                    {% if object.like3.all.count %}
                    <span>
                        {{object.like3.all.count}}
                    </span>
                    {% endif %}
                    <a href="{% url 'photo:like4' object.id %}" class="">좋아요4!</a>
                    {% if object.like4.all.count %}
                    <span>
                        {{object.like4.all.count}}
                    </span>
                    {% endif %}
                    <a href="{% url 'photo:like5' object.id %}" class="">좋아요5!</a>
                    {% if object.like5.all.count %}
                    <span>
                        {{object.like5.all.count}}
                    </span>
                    {% endif %}
                    <br>
                    수정일 : {{ object.updated }}
                </li>
                <li>생성일 : {{ object.created }}</li>
                
            </ul>
            <div>
                <a href = "{% url 'comment_new' object.id %}">댓글쓰기</a>
                <a href="{% url 'photo:update' object.id %}">수정하기</a>
                <a href="{% url 'photo:delete' object.id %}">삭제하기</a>
            </div>
            <ul>
                {% for comment in object.comment_set.all %}
                    <li>
                        {{ comment.comment_text }}
                        by {{ comment.author }}
                        at {{ comment.comment_date }}
                        <br>
                        {% if comment.author == request.user %}
                            <a href="{{ comment.get_edit_url }}">
                                댓글 수정
                            </a>
                            <a href="{{ comment.get_delete_url }}" >
                                댓글 삭제
                            </a>                            
                        {% endif %}
                    </li>
                {% endfor %}
            </ul>
        </div>
    </div>
    <div></div>
</div>
{% endblock %}

백엔드/Test_project/photo/templates/photo/photo_list.html
{% extends 'base.html' %}
{% block title %}
{% endblock %}

{% block content %}

<div>
    <div>
        <div></div>
        <div>
            {% for object in object_list %}
            <div>
                <div>
                    {{ object.author }}
                </div>
                <img src="{{ object.image.url }}">
                <div>
                    <p>{{ object.text }}</p>
                </div>
                <ul>
                    <li>
                        <a href="{% url 'photo:like1' object.id %}" class="">좋아요!</a>
                        {% if object.like1.all.count %}
                        <span>
                            {{object.like1.all.count}}
                        </span>
                        {% endif %}
                        <a href="{% url 'photo:like2' object.id%}" class="">좋아요2!</a>
                        {% if object.like2.all.count %}
                        <span>
                            {{object.like2.all.count}}
                        </span>
                        {% endif %}
                        <a href="{% url 'photo:like3' object.id%}" class="">좋아요3!</a>
                        {% if object.like3.all.count %}
                        <span>
                            {{object.like3.all.count}}
                        </span>
                        {% endif %}
                        <a href="{% url 'photo:like4' object.id%}" class="">좋아요4!</a>
                        {% if object.like4.all.count %}
                        <span>
                            {{object.like4.all.count}}
                        </span>
                        {% endif %}
                        <a href="{% url 'photo:like5' object.id%}" class="">좋아요5!</a>
                        {% if object.like5.all.count %}
                        <span>
                            {{object.like5.all.count}}
                        </span>
                        {% endif %}
                        생성일 : {{ object.created }}
                    </li>
                    <li>수정일 : {{ object.updated }}</li>
                </ul>
                <div>
                    <a href="{% url 'photo:detail' object.id %}">댓글달기</a>
                    {% if user == object.author %}
                    <a href="{% url 'photo:update' object.id %}">수정하기</a>
                    <a href="{% url 'photo:delete' object.id %}">삭제하기</a>
                    {% endif %}
                </div>
            </div>
            {% endfor %}
        </div>
        <div></div>
    </div>
</div>
{% endblock %}

백엔드/Test_project/photo/templates/photo/photo_update.html
{% extends 'base.html' %}
{% block content %}
<div>
    <div></div>
    <div>
        <form action="" method="post">
            {% csrf_token %}
            {{form.as_p}}
            <input type="submit" value="Create">
        </form>
    </div>
    <div></div>
</div>
{% endblock %}