백엔드/instargram/accounts/urls.py
from django.urls import path,include
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib import admin
from django.contrib.auth import views as auth_views
import accounts.views

import board.views
app_name = "accounts"

urlpatterns = [
    path('main/', LoginView.as_view(template_name = 'login.html'), name='login'),
    path('logout/', LogoutView.as_view(template_name = 'logout.html'), name='logout'),
]

백엔드/instargram/instargram/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings#내 세팅을 가져와라
from django.conf.urls.static import static#url들을 가져와라

import frontend.views#블로그안에 있는 views라는 파이썬 파일을 가져옴
import board.views
import accounts.views
from accounts import views
import photo.views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('photo.urls')),
    path('accounts/', include('accounts.urls')),
    path('read/', photo.views.read, name = "read"),
    path('main/', photo.views.main, name="main"),
    path('bulletin/', photo.views.bulletin, name="bulletin"),
    path('bulletin/intro/', photo.views.bulletinIntro, name="bulletinIntro"),
    path('bulletin/menu/', photo.views.bulletinMenu, name="bulletinMenu"),
    path('bulletin/map/', photo.views.bulletinMap, name="bulletinMap"),
    path('bulletin/com/', photo.views.bulletinComment, name="bulletinComment"),
    path('new1/',photo.views.new1, name="new1"),
    path('pr2/',photo.views.pr2, name="pr2"),
    path('pr3/',photo.views.pr3, name="pr3"),
    path('pr22/',photo.views.pr22, name="pr22"),
    path('pratice/',photo.views.pratice, name="pratice"),
    path('accounts/',include('allauth.urls')),
    path('logout/',photo.views.logout,name='logout'),
    path('123/',frontend.views.read1,name="read1"),
    path('login1/',frontend.views.login1,name="login1"),
    path(r'^(?P<post_pk>\d+)/comment/new/$',photo.views.comment_new,name='comment_new'), 
    path(r'^(?P<post_pk>\d+)/comment/(?P<pk>\d+)/edit/$',photo.views.comment_edit,name='comment_edit'), 
    path(r'^(?P<post_pk>\d+)/comment/(?P<pk>\d+)/delete/$',photo.views.comment_delete,name='comment_delete'), 
]

백엔드/instargram/photo/urls.py
from django.contrib import admin
from django.urls import path
from .views import PhotoList, PhotoDelete, PhotoDetail, PhotoUpdate, PhotoCreate, PhotoLike, Photofavorite, PhotoLikeList, PhotoFavoriteList, PhotoSortLike,PhotoSortMine   

app_name = "photo"
urlpatterns = [
    path('create/', PhotoCreate.as_view(), name='create'),
    path("delete/<int:pk>/", PhotoDelete.as_view(), name='delete'),
    path("update/<int:pk>/", PhotoUpdate.as_view(), name='update'),
    path("detail/<int:pk>/", PhotoDetail.as_view(), name='detail'),
    path("like/<int:photo_id>/", PhotoLike.as_view(), name="like"),
    path("favorite/<int:photo_id>", Photofavorite.as_view(), name="favorite"),
    path("", PhotoList.as_view(), name='index'),
    path("like/",PhotoLikeList.as_view(),name='like_list'),
    path("favorite/",PhotoFavoriteList.as_view(),name='favorite_list'),
    path("sort_like/",PhotoSortLike.as_view(),name='sort_like'),
    path("sort_mypost/",PhotoSortMine.as_view(),name='sort_mine'),
]

from django.conf.urls.static import static
from django.conf import settings

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

백엔드/instargram/photo/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse
from django.contrib.auth import get_user_model
# Create your models here.
from django.utils import timezone
from django import forms
from django.conf import settings

class Photo(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user')
    text = models.TextField(blank=True)
    image = models.ImageField(upload_to= 'timeline_photo/%Y/%m/%d')
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    like = models.ManyToManyField(User, related_name = 'like_post', blank=True)
    favorite = models.ManyToManyField(User, related_name='favorite_post', blank=True)


    def approve(self):
        self.approved_comment = True
        self.save()

    def __str__(self):
        return "text : "+self.text


    def get_absolute_url(self):
        return reverse('photo:detail', args=[self.id])



class Blog(models.Model):
    title = models.CharField(max_length=200)
    pub_date = models.DateTimeField("data published")
    body = models.TextField()

    def __str__(self):
        return self.title

    def summary(self):
        return str(self.body)[:100]

    def pretty_pub_date(self):
        return self.pub_date.strftime("%y.%m.%d")

class Comment(models.Model):
    photo = models.ForeignKey(Photo,on_delete=True, null=True)
    author = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=True, null=True)
    comment_date = models.DateTimeField(default=timezone.now)
    comment_text = models.TextField()
    
    class Meta:
        ordering = ['comment_date'] #id역순으로 정렬이에용
    
    def get_edit_url(self):
        return reverse('comment_edit', args=[self.photo.pk,  self.pk])

    def get_delete_url(self):
        return reverse('comment_delete', args=[self.photo.pk,  self.pk])

백엔드/instargram/photo/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic.list import ListView
from django.views.generic.edit import UpdateView, CreateView, DeleteView
from django.views.generic.detail import DetailView
from django.http import HttpResponseRedirect, HttpResponseForbidden
from django.contrib import messages
from django.views.generic.base import View
from django.utils import timezone
from django.contrib.auth.models import User#user만드는 함수들 가져와
from django.contrib import auth
from django.core.paginator import Paginator,PageNotAnInteger,EmptyPage
from urllib.parse import urlparse

from django.contrib.auth.decorators import login_required
from hitcount.views import HitCountDetailView
from .models import Photo, Comment
from .forms import CommentForm
from django.db.models import Count

# Create your views here.

class PhotoSortLike(ListView):
    model = Photo
    template_name = 'photo/photo_list.html'


    def get_queryset(self):
        user = self.request.user
        queryset = Photo.objects.annotate(like_count=Count('like')).order_by('-like_count')  
        return queryset

class PhotoSortMine(ListView):
    model = Photo
    template_name = 'photo/photo_list.html'


    def get_queryset(self):
        user = self.request.user
        queryset = Photo.objects.filter(author=user)
        return queryset

def view(request, no=0):
    if no == 0: return HttpResponseRedirect('/')

    board = Board.objects.filter(id=no)
    board.update(hit=F('hit')+1)
    data = {
        'board':board[0]
    }
    return render(request, 'board/view.html', data)

class PhotoList(ListView):
    model = Photo
    template_name_suffix = '_list'
    paginate_by = 9
    count_hit = True
    
    def get_queryset(self):
        user = self.request.user
        queryset = Photo.objects.all().order_by('-created')
        return queryset

class PhotoCreate(CreateView):
    model = Photo
    fields = ['text', 'image']
    template_name_suffix = '_create'
    success_url = "/"

    def form_valid(self, form):
        form.instance.author_id = self.request.user.id
        if form.is_valid():
            form.instance.save()
            return redirect('/')
        else:
            return self.render_to_response({'form': form})

class PhotoUpdate(UpdateView):
    model = Photo
    fields = ['author', 'text', 'image']
    template_name_suffix = '_update'
    #success_url = "/"

    def dispatch(self, request, *args, **kwargs):
        object = self.get_object()
        if object.author != request.user:
            messages.warning(request, '수정할 권한이 없습니다.')
            return HttpResponseRedirect('/')
            # 삭제 페이지에서 권한이 없다! 라고 띄우거나
            # detail페이지로 들어가서 삭제에 실패했습니다. 라고 띄우거나
        else:
            return super(PhotoUpdate, self).dispatch(request, *args, **kwargs)

class PhotoDelete(DeleteView):
    model = Photo
    template_name_suffix = '_delete'
    success_url = "/"

    def dispatch(self, request, *args, **kwargs):
        object = self.get_object()
        if object.author != request.user:
            messages.warning(request, '삭제할 권한이 없습니다.')
            return HttpResponseRedirect('/')
        else:
            return super(PhotoDelete, self).dispatch(request, *args, **kwargs)

class PhotoDetail(DetailView):
    model = Photo
    template_name_suffix = '_detail'
    
class PhotoLike(View):
    def get(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return HttpResponseForbidden()
        else:
            if 'photo_id' in kwargs:
                photo_id = kwargs['photo_id']
                photo = Photo.objects.get(pk=photo_id)
                user = request.user
                if user in photo.like.all():
                    photo.like.remove(user)
                else:
                    photo.like.add(user)
            referer_url = request.META.get('HTTP_REFERER')
            path = urlparse(referer_url).path
            return HttpResponseRedirect(path)

class Photofavorite(View):
    def get(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return HttpResponseForbidden()
        else:
            if 'photo_id' in kwargs:
                photo_id = kwargs['photo_id']
                photo = Photo.objects.get(pk=photo_id)
                user = request.user
                if user in photo.favorite.all():
                    photo.favorite.remove(user)
                else :
                    photo.favorite.add(user)
            return HttpResponseRedirect('/')

class PhotoLikeList(ListView):
    model = Photo
    template_name = 'photo/photo_list.html'

    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            messages.warning(request, '로그인을 먼저하세요')
            return HttpResponseRedirect('/')
        return super(PhotoLikeList, self).dispatch(request, *args, **kwargs)

    def get_queryset(self):
        user = self.request.user
        queryset = user.like_post.all()
        return queryset


class PhotoFavoriteList(ListView):
    model = Photo
    template_name = 'photo/photo_list.html'

    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            messages.warning(request, '로그인을 먼저하세요')
            return HttpResponseRedirect('/')
        return super(PhotoFavoriteList, self).dispatch(request, *args, **kwargs)

    def get_queryset(self):
        user = self.request.user
        queryset = user.favorite_post.all()
        return queryset

def read(request):#blog 함수임
    return render(request, "read.html")

def main(request):
    return render(request, "main.html")
    
def bulletin(request):
    return render(request, "bulletin.html")

def bulletinMenu(request):
    return render(request, "bulletin_menu.html")

def bulletinIntro(request):
    return render(request, "bulletin_introduce.html")

def bulletinMap(request):
    return render(request, "bulletin_map.html")

def bulletinComment(request):
    return render(request, "bulletin_comment.html")

def new1(request):
    return render(request, "new1.html")

def pr2(request):
    return render(request, "pr2.html")
    
    
def pr22(request):
    return render(request, "pr22.html")
    
def pr3(request):
    return render(request, "pr3.html")

def pratice(request):
    return render(request, "pratice.html")

def logout(request):
    auth.logout(request)
    return redirect('/main')

def index(request):
    sort = request.GET.get('sort','')
    if sort == 'likes':
        memos = Photo.objects.annotate(like=Count('likes')).order_by('-like', '-updated')
        return render(request, 'photo_list.html', {'memos' : memos})
    elif sort == 'mypost':
        user = request.user
        memos = Photo.objects.filter(name_id = user).order_by('-updated') #복수를 가져올수 있음
        return render(request, 'photo_list.html', {'memos' : memos})
    else:
        memos = Photo.objects.order_by('-updated')
        return render(request, 'photo_list.html', {'memos' : memos})

def comment_detail(request, photo_id):
    comment_detail = get_object_or_404(Photo, pk=photo_id)
    comments = Comment.objects.filter(photo_id=photo_id)

    context = {
        'comment_detail' : comment_detail,
        'comments' : comments
    }

    return render(request, 'photo_detail.html', context)

def comment_new(request, post_pk):
    post = get_object_or_404(Photo, pk=post_pk)
    
    if request.method == 'POST':
        form = CommentForm(request.POST, request.FILES)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.photo = post
            comment.author = request.user
            comment.save()  
            return redirect('/detail/' + str(post_pk))
    else:
        form = CommentForm()
    return render(request,'comment_form.html',{'form':form})

def comment_edit(request, post_pk,pk):
    comment = get_object_or_404(Comment, pk=pk)
    
    if comment.author != request.user:
        return redirect('detail',post_pk)
    
    if request.method == 'POST':
        form = CommentForm(request.POST, request.FILES,instance=comment)
        if form.is_valid():
            comment = form.save()
            return redirect('photo:detail',comment.photo.pk)
    else:
        form = CommentForm(instance=comment)
    return render(request,'comment_form.html',{'form':form})

    
def comment_delete(request, post_pk,pk):
    comment = get_object_or_404(Comment, pk=pk)
    #작성자만 삭제가능
    if comment.author != request.user:
        return redirect('photo:detail',post_pk)

    if request.method == 'POST':
        comment.delete()
        return redirect('photo:detail',post_pk)

    return render(request,'comment_confirm_delete.html',{'comment':comment,})

백엔드/instargram/photo/templates/photo/photo_create.html
{% extends 'base.html' %}
{% block content %}
<div class="row">
    <div class="col"></div>
    <div class="col-12 col-xl-8 col-md-8">
        <div class="alert alert-primary" role="alert">
            모든 부분을 다 채워넣어주세요!!
        </div>
        <form action="" method="post" enctype='multipart/form-data'>
            % csrf_token %}
            {{form.as_p}}
            <form>
            <p>---------------------------------------------------------------------------------------------</p>
            <p>지역을 선택해주세요</p>
            <select name="fruit">
                <option value="local_half" selected> 중구 
                <option value="local_north"> 북구
                <option value="local_west"> 서구
                <option value="local_east"> 동구
                <option value="local_south"> 남구
                <option value="local_soosung"> 수성구
                <option value="local_dalsu"> 달서구
                </select>
            </form>
            <p><input type="submit" value="Upload" class="btn btn-pirmary"style="border:1px solid black;"></p>
        </form>
    </div>
    <div class="col"></div>
</div>
{% endblock %}

백엔드/instargram/photo/templates/photo/photo_delete.html
{% extends 'base.html' %}
{% block content %}
<div class="alert alert-primary" role="alert">
    진짜로 {{object}}를 지우실 건가요?
</div>
<form action="" method ="post">
    {% csrf_token %}
    <input type="submit" value="Delete OK">
</form>
{% endblock %}

백엔드/instargram/photo/templates/photo/photo_detail.html
{% extends 'base.html' %}
{% block title %}
{% endblock %}

{% block content %}
<div class="row">
    <div class="col"></div>
    <div class="col-12 col-xl-4 col-md-4">
        <div class="card" style="width: 30rem;">
            <img src="{{object.image.url}}" class="card-img-top" alt="...">
            <div class="card-body">
                <h5 class="card-title">{{object.author}}</h5>
                <p class="card-text">{{object.text}}</p>
            </div>
            
            <div class="card-body">
                <a href="{% url 'photo:update' object.id %}" class="card-link">수정하기</a>
                <a href="{% url 'photo:delete' object.id %}" class="card-link">삭제하기</a>               
            </div>
            <ul class="list-group-flush">
                <li class="list-group-item">
                    <a href="{% url 'photo:like' object.id%}" class="">좋아요!</a>
                    {% if object.like.all.count %}
                    <span class = "float-left">
                        {{object.like.all.count}}
                    </span>
                    {% endif %}
                    <br>
                    <a href="{% url 'photo:favorite' object.id%}" class="">저장하기!</a>
                    <br>
                    <a href = "{% url 'comment_new' object.id %}">댓글쓰기</a>
                </li>
                
                <ul>
                    {% for comment in object.comment_set.all %}
     
                        <li>
                            {{ comment.comment_text }}
                            by {{ comment.author }}
                            at {{ comment.comment_date }}
                            <br>
                            {% if comment.author == request.user %}
                                <a href="{{ comment.get_edit_url }}">
                                    댓글 수정
                                </a>
                                <a href="{{ comment.get_delete_url }}" >
                                    댓글 삭제
                                </a>
                            {% endif %}
                        </li>
     
                    {% endfor %}
                </ul>
                <li class="list-group-item">생성일 : {{object.created}}</li>

            </ul>
        </div>
    </div>

    <div class="col"></div>
</div>







<form action="{ % url "board:comment" object.id % }" method="POST">
{% csrf_token %}
    
        
    <input type="submit" value="Comment" class="btn btn-outline-primary">
    
</form>


{% endblock %}

백엔드/instargram/photo/templates/photo/photo_list.html
{% extends 'base.html' %}
<head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">     
  </head>
  {% load static %}  
{% block content %}

<body>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>

<!DOCTYPE html>
<html lang="ko">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>hagusa cafe</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
        <style>
            p { margin:20px 0px; }
        </style>
    </head>
    
    <link href = "{% static 'css/homecss.css' %}" rel = "stylesheet">
    <body>
    <div id="m3">
        <div id ="read_title"><center>.....</div>
        <form>
            <input type="search" placeholder="Search" aria-label="Search" size ="30">
            <input type="submit"  value="" style="background-color:transparent;  border:0px transparent solid;"></button>
        </form>
        <select id="sort-select" style="margin-left:85%;" onchange="location = this.value;">
                <option>정렬</option>
                <option class="sort-date" value="/">최신순</option>
                <option class="sort-likes" value="/sort_like">좋아요순</option>
                {% if user.is_authenticated %}
                <option class="sort-mypost" value="/sort_mypost">내가쓴글</option>
                {% endif %}
        </select>
        <div id="read_category">
            <br>

            


            <div id="read_blank1"></div>
            {% for object in object_list %}
                <div id="read_card"><center></center>
                    <a href="{% url 'photo:detail' object.id %}" class=""style="font-size:12px;">
                        <img src="{{ object.image.url }}" class="card-img-top"style="width:225px;height:150px;"><br>                    
                            <div id="card_content">
                                <h10 class="card-title">{{object.author}}</h10><br>
                                    <h10>좋아요 :{{object.like.all.count}}</h10><br>
                                    
                                    <a class="card-text"style="font-size:15px;">{{object.text}}</a><br>
                                    
                                    

                            </div>
                    </a>
                </div>
                {% if forloop.counter|divisibleby:3 %}
                    <div id="read_jul"></div>
                    <div id="read_blank1"></div>
                {% else %}
                    <div id="read_blank"></div>
                {% endif %}
            {% endfor %}
        </div>
    </div>

    </body>
</html>
{% endblock %}

백엔드/instargram/photo/templates/photo/photo_lost.html
<head>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">     
</head>
{% load static %}

<body>
  {% load static %}
  <style>
    .btn-like{
      display: inline-block;
      width: 45px;
      height: 40px;
      background:url({% static 'images/instargram_img.png' %});
      background-position: -285px -140px;
      text-indent: -9999px;
      overflow:hidden;
      border:none;
    }
    .btn-like.active{
      display: inline-block;
      width: 50px;
      height: 50px;
      background:url({% static 'images/instargram_img.png' %});
      background-position: -50px -400px;
      text-indent: -9999px;
      overflow:hidden;
      border:none;
    }
    .btn-favorite{
      display: inline-block;
      width: 50px;
      height: 50px;
      background:url({% static 'images/instargram_img.png' %});
      background-position: -290px 350px;
      text-indent: -9999px;
      overflow:hidden;
      border:none;
    }
    .btn-favorite.active{
      display: inline-block;
      width: 50px;
      height: 50px;
      background:url({% static 'images/instargram_img.png' %});
      background-position: -515px -100px;
      text-indent: -9999px;
      overflow:hidden;
      border:none;
    }
  </style>

<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Dstagram</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'photo:index' %}">Home <span class="sr-only">(current)</span></a>
      </li>
      {% load socialaccount %}
      {% providers_media_js %}

      {% if user.is_authenticated %}
      <li class="nav-item">
        <a class="nav-link" href="{% url 'photo:create' %}">게시글 작성</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'accounts:logout' %}">Logout</a>
      </li> 
      {% else %}
      <li class="nav-item active">
        <a class="nav-link" href="{% provider_login_url 'google' %}">Login <span class="sr-only">(current)</span></a>
      </li>
      {% endif %}
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Dropdown
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>
<div class="container">
  {% if messages %}
  <div class="row">
    <div class="col"></div>
    <div class="col-6">
      {% for message in messages %}
      <div class="alert alert-{{message.tag}}">{{message}}</div>
      {% endfor %}
    </div>
    <div class="col"></div>
  </div>
</div>
  {% endif %}

{% block content %}


<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>

<!DOCTYPE html>
<html lang="ko">

  <head>
  <meta charset="UTF-8">
  <link href = "{% static 'css/homecss.css' %}" rel = "stylesheet">
  <title>Hagusa</title>
  </head>
  <body>
  <div id="m3">
      <div id ="read_title"><center>.....</div>
      <form>
          <input type="search" placeholder="Search" aria-label="Search" size ="30">
          <input type="submit"  value="" style="background-color:transparent;  border:0px transparent solid;"></button>
      </form>
      <div id="read_category">
          <br>
          
          <h1>
              <div id="read_blank1"></div>
              <div id="read_card"><center>
                  <img src="../static/images/백꿈.png" class="card-img-top"style="width:225px;height:150px;"><br>
                      <div id="card_content">
                          <h10 class="card-title">title</h10><br>
                          <a class="card-text"style="font-size:15px;">설명글</a><br>
                          <a href="#" class="btn btn-primary"style="font-size:12px;">Go somewhere</a>
                      </div>
              </div>
              </div>
          </h1>
      </div>
  </div>
  </body>
</html>
{% endblock %}

백엔드/instargram/photo/templates/photo/photo_update.html
{% extends 'base.html' %}
{% block content %}
<div class="row">
    <div class="col"></div>
    <div class="col-12 col-xl-8 col-md-8">
        <form action="" method="post">
            {% csrf_token %}
            {{form.as_p}}
            <input type="submit" value="Create">
        </form>
    </div>
    <div class="col"></div>
</div>
{% endblock %}