백엔드/instargram/instargram/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings#내 세팅을 가져와라
from django.conf.urls.static import static#url들을 가져와라

import frontend.views#블로그안에 있는 views라는 파이썬 파일을 가져옴
import board.views
import accounts.views
from accounts import views
import photo.views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('photo.urls')),
    path('accounts/', include('accounts.urls')),
    path('read/', photo.views.read, name = "read"),
    path('main/', photo.views.main, name="main"),
    path('bulletin/', photo.views.bulletin, name="bulletin"),
    path('bulletin/intro/', photo.views.bulletinIntro, name="bulletinIntro"),
    path('bulletin/menu/', photo.views.bulletinMenu, name="bulletinMenu"),
    path('bulletin/map/', photo.views.bulletinMap, name="bulletinMap"),
    path('bulletin/com/', photo.views.bulletinComment, name="bulletinComment"),
    path('new1/',photo.views.new1, name="new1"),
    path('pr2/',photo.views.pr2, name="pr2"),
    path('pr3/',photo.views.pr3, name="pr3"),
    path('pr22/',photo.views.pr22, name="pr22"),
    path('pratice/',photo.views.pratice, name="pratice"),
    path('accounts/',include('allauth.urls')),
    path('logout/',photo.views.logout,name='logout'),
    path('123/',frontend.views.read1,name="read1"),
    path('login1/',frontend.views.login1,name="login1"),
    path(r'^(?P<post_pk>\d+)/comment/new/$',photo.views.comment_new,name='comment_new'), 
    path(r'^(?P<post_pk>\d+)/comment/(?P<pk>\d+)/edit/$',photo.views.comment_edit,name='comment_edit'), 
    path(r'^(?P<post_pk>\d+)/comment/(?P<pk>\d+)/delete/$',photo.views.comment_delete,name='comment_delete'), 
]

백엔드/instargram/photo/urls.py
from django.contrib import admin
from django.urls import path
from .views import PhotoList, PhotoDelete, PhotoDetail, PhotoUpdate, PhotoCreate, PhotoLike, Photofavorite, PhotoLikeList, PhotoFavoriteList, PhotoSortLike,PhotoSortMine   

app_name = "photo"
urlpatterns = [
    path('create/', PhotoCreate.as_view(), name='create'),
    path("delete/<int:pk>/", PhotoDelete.as_view(), name='delete'),
    path("update/<int:pk>/", PhotoUpdate.as_view(), name='update'),
    path("detail/<int:pk>/", PhotoDetail.as_view(), name='detail'),
    path("like/<int:photo_id>/", PhotoLike.as_view(), name="like"),
    path("favorite/<int:photo_id>", Photofavorite.as_view(), name="favorite"),
    path("", PhotoList.as_view(), name='index'),
    path("like/",PhotoLikeList.as_view(),name='like_list'),
    path("favorite/",PhotoFavoriteList.as_view(),name='favorite_list'),
    path("sort_like/",PhotoSortLike.as_view(),name='sort_like'),
    path("sort_mypost/",PhotoSortMine.as_view(),name='sort_mine'),
]

from django.conf.urls.static import static
from django.conf import settings

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

백엔드/instargram/frontend/models.py
from django.db import models

# Create your models here.
class Blog(models.Model):
    title = models.CharField(max_length=200)
    pub_date = models.DateTimeField("data published")
    body = models.TextField()

    def __str__(self):
        return self.title

    def summary(self):
        return str(self.body)[:100]

    def pretty_pub_date(self):
        return self.pub_date.strftime("%y.%m.%d")

백엔드/instargram/frontend/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Blog
from django.utils import timezone

from django.contrib.auth.models import User#user만드는 함수들 가져와
from django.contrib import auth

# Create your views here.
def read(request):#blog 함수임
    return render(request, "read.html")

def read1(request):
    return render(request, "read1.html")

def main(request):
    return render(request, "main.html")
    
def bulletin(request):
    return render(request, "bulletin.html")

def bulletinMenu(request):
    return render(request, "bulletin_menu.html")

def bulletinIntro(request):
    return render(request, "bulletin_introduce.html")

def bulletinMap(request):
    return render(request, "bulletin_map.html")

def bulletinComment(request):
    return render(request, "bulletin_comment.html")

def new1(request):
    return render(request, "new1.html")

def pr2(request):
    return render(request, "pr2.html")

def pratice(request):
    return render(request, "pratice.html")

def logout(request):
    auth.logout(request)
    return redirect('/main')

def login1(request):
    return render(request, "login1.html")

백엔드/instargram/frontend/templates/bulletin.html
{% load static %}
<html>
    <head>
        <link href = "{% static 'css/test.css' %}" rel = "stylesheet">
    </head>
    <body>
        <div id="m3">
            <div id="m2">
                <div id="main_title">
                    <a href="#" class="item" >login</a>
                    <a href="#" class="item" >signup</a>
                    <a href="#" class="item" style="margin-right:20%;">목록으로</a>
                </div>
                <div id="read_title"></div>
                    <div id="m1"><center></div>
                    <div id="bulletin_detail">
                        <div id="bulletin_select_detail_introduce"><a href="#" class="item">소개</a></div>
                        <div id="bulletin_select_detail_menu"><a href="#" class="item">메뉴</a></div>
                        <div id="bulletin_select_detail_map"><a href="#" class="item">위치</a></div>
                        <div id="bulletin_select_detail_comment"><a href="#" class="item">댓글</a></div>
                    </div>
                </div>
            </div>
        </div>    
    </body>
</html>

백엔드/instargram/frontend/templates/index.html
{% load static %}
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>CSS Image Maps</title>
<style type="text/css">

#container {
	width: 580px;
	height: 268px;
	margin: 0 auto;
}

h1 {
	margin-bottom: 20px;
	border-bottom: 2px solid #000;
	font: bold 28px Arial, Helvetica, sans-serif;
	text-align: center;
	padding-bottom: 5px;
}

h1 a {
	color: #000;
	text-decoration: none;
}

ul#continents1, ul#continents2, ul#continents3 {
	list-style: none;
	width: 580px;
	height: 268px;
	position: relative;
	background: url(../images/map.png) no-repeat 0 0;
}

ul#continents1 li, ul#continents2 li, ul#continents3 li {
	position: absolute;
}

.northamerica {
	width: 227px;
	height: 142px;
	top: 2px;
	left: 0px;
}

.southamerica {
	width: 108px;
	height: 130px;
	top: 131px;
	left: 76px;
}

.africa {
	width: 120px;
	height: 140px;
	top: 83px;
	left: 209px;
}

.europe {
	width: 120px;
	height: 84px;
	top: 1px;
	left: 211px;
}

.asia {
	width: 215px;
	height: 175px;
	top: 1px;
	left: 283px;
}

.australia {
	width: 114px;
	height: 95px;
	top: 152px;
	left: 432px;
}

ul#continents1 li a, ul#continents2 li a, ul#continents3 li a  {
	display: block;
	outline: none;
	height: 100%;
}

ul#continents1 li a, ul#continents2 li a  {
	text-indent: -9000px;
}

ul#continents2 li a:hover, ul#continents3 li a:hover {
	background: url(images/map.png) no-repeat 0 0;	
}

ul#continents2 li.northamerica a:hover, ul#continents3 li.northamerica a:hover {
	background-position: 0 -270px;
}

ul#continents2 li.southamerica a:hover, ul#continents3 li.southamerica a:hover {
	background-position: -226px -273px;
}

ul#continents2 li.africa a:hover, ul#continents3 li.africa a:hover {
	background-position: -209px -417px;
}

ul#continents2 li.europe a:hover, ul#continents3 li.europe a:hover {
	background-position: -22px -427px;
}

ul#continents2 li.asia a:hover, ul#continents3 li.asia a:hover {
	background-position: -363px -268px;
}

ul#continents2 li.australia a:hover, ul#continents3 li.australia a:hover {
	background-position: -412px -455px;
}

ul#continents3 li a span {
	display: none;
}

ul#continents3 li a:hover span {
	display: block;
}

ul#continents3 li a:hover span {
	display: block;
	padding: 5px;
	width: 150px;
	background: #000;
	position: relative;
	top: 50%;
	font: 11px Arial, Helvetica, sans-serif;
	opacity: .75;
	filter:alpha(opacity=75);
	color: #FFF;
}

ul#continents3 li a:hover span strong {
	display: block;
	margin-bottom: 2px;
	font-size: 12px;
	text-decoration: underline;
}
</style>
</head>

<body>
More script and css style
: <a href="http://www.htmldrive.net/" title="HTML DRIVE - Free DHMTL Scripts,Jquery plugins,Javascript,CSS,CSS3,Html5 Library">www.htmldrive.net </a>
<div id="container">
	<h1><a href="http://www.noobcube.com/tutorials/html-css/css-image-maps-a-beginners-guide-/" title="Visit the Noobcube Tutorial on CSS Image Maps">Simple CSS Image Map</a>		</h1>

    <ul id="continents1">
        <li class="northamerica"><a href="http://en.wikipedia.org/wiki/North_America">North America</a></li>
        <li class="southamerica"><a href="http://en.wikipedia.org/wiki/South_America">South America</a></li>    
        <li class="asia"><a href="http://en.wikipedia.org/wiki/Asia">Asia</a></li>
        <li class="australia"><a href="http://en.wikipedia.org/wiki/Australia">Australia</a></li>
        <li class="africa"><a href="http://en.wikipedia.org/wiki/Africa">Africa</a></li>
        <li class="europe"><a href="http://en.wikipedia.org/wiki/Europe">Europe</a></li>    
    </ul>

	<h1><a href="http://www.noobcube.com/tutorials/html-css/css-image-maps-a-beginners-guide-/" title="Visit the Noobcube Tutorial on CSS Image Maps">CSS Image Map w/Hover States</a>		</h1>
    <ul id="continents2">
        <li class="northamerica"><a href="http://en.wikipedia.org/wiki/North_America">North America</a></li>
        <li class="southamerica"><a href="http://en.wikipedia.org/wiki/South_America">South America</a></li>    
        <li class="asia"><a href="http://en.wikipedia.org/wiki/Asia">Asia</a></li>
        <li class="australia"><a href="http://en.wikipedia.org/wiki/Australia">Australia</a></li>

        <li class="africa"><a href="http://en.wikipedia.org/wiki/Africa">Africa</a></li>
        <li class="europe"><a href="http://en.wikipedia.org/wiki/Europe">Europe</a></li>    
    </ul>
	<h1><a href="http://www.noobcube.com/tutorials/html-css/css-image-maps-a-beginners-guide-/" title="Visit the Noobcube Tutorial on CSS Image Maps">CSS Image Map w/Tooltip on Hover</a>		</h1>
	<ul id="continents3">
    <li class="northamerica">
        <a href="http://en.wikipedia.org/wiki/North_America">

            <span>
                <strong>North America</strong> 
                Population: 528,720,588
            </span>
        </a>
    </li>
    <li class="southamerica">
   		<a href="http://en.wikipedia.org/wiki/South_America">
            <span>

                <strong>South America</strong>
                Population: 385,742,554
            </span>
        </a>
    </li>    
    <li class="asia">
    	<a href="http://en.wikipedia.org/wiki/Asia">
            <span>
                <strong>Asia</strong>

                Population: 3,879,000,000
            </span>
        </a>
    </li>
    <li class="australia">
    	<a href="http://en.wikipedia.org/wiki/Australia">
            <span>
                <strong>Australia</strong>
                Population: 21,807,000
            </span>

        </a>
    </li>
    <li class="africa">
        <a href="http://en.wikipedia.org/wiki/Africa">
        <span>
            <strong>Africa</strong>
            Population: 922,011,000
        </span>
        </a>

    </li>
    <li class="europe">
        <a href="http://en.wikipedia.org/wiki/Europe">
            <span>
                <strong>Europe</strong>
                Population: 731,000,000
            </span>
        </a>
    </li>    

</ul>
</div>
</body>
</html>

백엔드/instargram/frontend/templates/login1.html
<!DOCTYPE html>
{% load static %}
<html lang="ko">

    <head>
    <meta charset="UTF-8">
    <link href = "{% static '../static/css/login.css' %}" rel = "stylesheet">
    <title>Hagusa</title>
    </head>
    {% load static %}
    {% load socialaccount %}
    {% providers_media_js %}
    <body>
        <center>
        <div id="block"><center>
            <div id="inblock1"style="margin-top:60px;"><img src="../static/images/google.png"style="width:20px;height:20px;border-radius:10px;"><a href="{% provider_login_url 'google' %}">구글 로그인</a></div>
            <div id="inblock2"style="margin-top:20px;"><img src="../static/images/naver.png"style="width:20px;height:20px;border-radius:10px;">네이버 로그인</div>
            <div id="inblock3"style="margin-top:20px;"><img src="../static/images/facebook.png"style="width:20px;height:20px;border-radius:10px;">페이스북 로그인</div>
        </div>
    </body>
</html>

백엔드/instargram/frontend/templates/main.html
{% extends 'base.html' %}
{% block title %}
{% endblock %}

{% block content %}

<div class='container'>
    <div class="row">
        <div class="col"></div>
        <div class="col-5">
            {% for object in object_list %}

            <div class="card">
                <div class="card-header">
                    {{object.author}}
                </div>
                 <img src="{{ object.image.url }}" class="card-img-top" alt="..."> 
                <div class="card-body">
                    <p class="card-text">{{object.text}}</p>
                </div>
                <ul class="list-group list-group-flush">
                    <li class="list-group-item">
                        <a href="{% url 'photo:like' object.id %}" class="float-left btn-like {%if user in object.like.all %} acitve {% endif %}">좋아요!</a>
                        {% if object.like.all.count %}
                        <span class = "float-left">
                            {{object.like.all.count}}
                        </span>
                        {% endif %}
                        <a href="{% url 'photo:favorite' object.id %}" class="float-right btn-favorite {% if user in object.favorite.all %} active{%endif%}">저장하기!</a>
                    </li>
                    <li class="list-group-item">생성일 : {{object.created}}</li>
                </ul>
                <div class="card-body">
                    <a href="{% url 'photo:detail' object.id %}" class="card-link">댓글달기</a>
                    {% if user == object.author %}
                    <a href="{% url 'photo:update' object.id %}" class="card-link">수정하기</a>
                    <a href="{% url 'photo:delete' object.id %}" class="card-link">삭제하기</a>
                    {% endif %}
                </div>
            </div>
            {% endfor %}
           <div id="map1" style="width:20%;height:500px;"></div>
            <div id="m6">빈공간</div>
        </div>
        <div class="col"></div>
    </div>
</div>
{% endblock %}

백엔드/instargram/frontend/templates/pr2.html
<h1>dd</h1>

백엔드/instargram/frontend/templates/pr3.html
{% load static %}

<head> 
    <meta charset="UTF-8">

    <link href = "{% static 'css/menu3.css' %}" rel = "stylesheet">
    <link href = "{% static 'css/list.css' %}" rel = "stylesheet">
    
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

</head>

<body>
    <div class="nav">
        <div class="logo">
            <img src="../static/images/aae.jpg">
        </div>
        <div class="nav_but">
            <a href="">페이지1</a>
            <a href="">페이지2</a>
            <a href="">페이지3</a>
            <a href="">페이지4</a>
        </div>
    </div>
    
   <center>
    <div id="m2">
      <center>
      
      <div id = "content">
          
              <div class>
                  <div id="image1"> images</div>
                  <div id='explain'>
                        <p>게시글 쓰는란</p>
                  </div>
              </div> 

              <div class>
                <div id="image1"> images</div>
                <div id='explain'>게시글 쓰는란</div>
            </div> 

            <div class>
                <div id="image1"> imgaes</div>
                <div id='explain'>게시글 쓰는란</div>
            </div> 

<!--
            <section class = "service">
                    <div class = "text">
                        <h1>멋사</h1>
                        <p>dfdfd</p>
                        <button>more..</button>
                    </div>
                </div>
            </section>

-->

            <section class = "list_intro">
                <div class = "container">
                    <div class ="list_intro_left">
                        <h2>오프라인 카페를 추천해주는 사이트입니다</h2>
                        <h1>Hagusa X LIKELION</h1>
                        <p>* 개발 : 안재욱 김승환 김현지 김현민</p>
                        <p>* 문의 : 010 - xxxx - xxxx</p>
                        
                    </div>
                    
                </div>
            </section>


            </center>
        </div>
    </center>
</body>

백엔드/instargram/frontend/templates/pratice.html
<!--{% load static %}
<h1> new page </h1>

<head> 
  <link href = "{% static 'css/menu.css' %}" rel = "stylesheet">
</head>

<body>
   <center>
    <div>
      <center>
      <div id="name", style="padding:20px;"> paris in the rain</div>

      <div id = "content">
          <div class="item">1</div>
          <div class="item">2</div>
          <div class="item">3</div>p
          
          <br>

          <div class="item">5</div>
          <div class="item">6</div>
          <div class="item">7</div>
          <br>

          <div class="item">9</div>
          <div class="item">10</div>
          <div class="item">11</div>
          <br>

        </div>
      
    </center>
    </div>
   </center>

  </body>
  -->
  <!DOCTYPE HTML>
  <html>

   <h1>바보</h1>
  </html>

백엔드/instargram/frontend/templates/read.html
<!DOCTYPE html>
{% load static %}
<html lang="ko">

    <head>
    <meta charset="UTF-8">
    <link href = "{% static 'css/homecss.css' %}" rel = "stylesheet">
    <title>Hagusa</title>
    </head>
    <body>
    <div id="m3">
        <div id ="read_title"><center>.....</div>
        <form>
            <input type="search" placeholder="검색창" aria-label="Search" size ="30">
            <input type="submit"  value="" style="background-color:transparent;  border:0px transparent solid;"></button>
        </form>
        <div id="read_category">
            <h1>
                <div id="read_blank1"></div>
                <div id="read_card"><center>
                        <img src="../static/images/백꿈.png" class="card-img-top"style="width:225px;height:150px;"><br>
                        <div id="card_content">
                            <h10 class="card-title">title</h10><br>
                            <a class="card-text"style="font-size:15px;">설명글</a><br>
                            <a href="#" class="btn btn-primary"style="font-size:12px;">Go somewhere</a>
                        </div>
                </div>
                <div id="read_blank"></div>
                <div id="read_card"><center>
                        <img src="../static/images/백꿈.png" class="card-img-top"style="width:225px;height:150px;"><br>
                        <div id="card_content">
                            <h10 class="card-title">title</h10><br>
                            <a class="card-text"style="font-size:15px;">설명글</a><br>
                            <a href="#" class="btn btn-primary"style="font-size:12px;">Go somewhere</a>
                        </div>
                </div>
                <div id="read_blank"></div>
                <div id="read_card"><center>
                    
                        <img src="../static/images/백꿈.png" class="card-img-top"style="width:225px;height:150px;"><br>
                        <div id="card_content">
                            <h10 class="card-title">title</h10><br>
                            <a class="card-text"style="font-size:15px;">설명글</a><br>
                            <a href="#" class="btn btn-primary"style="font-size:12px;">Go somewhere</a>
                        </div>
                      
                </div>
            </h1>
            <div id="read_jul"></div>
            <h1>
                <div id="read_center">
                    <div id="read_blank1"></div>
                    <div id="read_card"><center>
                        
                            <img src="../static/images/백꿈.png" class="card-img-top"style="width:225px;height:150px;"><br>
                            <div id="card_content">
                                <h10 class="card-title">title</h10><br>
                                <a class="card-text"style="font-size:15px;">설명글</a><br>
                                <a href="#" class="btn btn-primary"style="font-size:12px;">Go somewhere</a>
                            </div>
                        
                    </div>
                    <div id="read_blank"></div>
                    <div id="read_card"><center>
                            <img src="../static/images/백꿈.png" class="card-img-top"style="width:225px;height:150px;"><br>
                            <div id="card_content">
                                <h10 class="card-title">title</h10><br>
                                <a class="card-text"style="font-size:15px;">설명글</a><br>
                                <a href="#" class="btn btn-primary"style="font-size:12px;">Go somewhere</a>
                            </div>
                    </div>
                    <div id="read_blank"></div>
                    <div id="read_card"><center>
                            <img src="../static/images/백꿈.png" class="card-img-top"style="width:225px;height:150px;"><br>
                            <div id="card_content">
                                <h10 class="card-title">title</h10><br>
                                <a class="card-text"style="font-size:15px;">설명글</a><br>
                                <a href="#" class="btn btn-primary"style="font-size:12px;">Go somewhere</a>
                            </div>
                    </div>
                </div>
            </h1>
            <div id="read_jul"></div>
            <h1>
                <div id="read_below">
                    <div id="read_blank1"></div>
                    <div id="read_card"><center>
                            <img src="../static/images/백꿈.png" class="card-img-top"style="width:225px;height:150px;"><br>
                            <div id="card_content">
                                <h10 class="card-title">title</h10><br>
                                <a class="card-text"style="font-size:15px;">설명글</a><br>
                                <a href="#" class="btn btn-primary"style="font-size:12px;">Go somewhere</a>
                            </div>
                    </div>
                    <div id="read_blank"></div>
                    <div id="read_card"><center>
                            <img src="../static/images/백꿈.png" class="card-img-top"style="width:225px;height:150px;"><br>
                            <div id="card_content">
                                <h10 class="card-title">title</h10><br>
                                <a class="card-text"style="font-size:15px;">설명글</a><br>
                                <a href="#" class="btn btn-primary"style="font-size:12px;">Go somewhere</a>
                            </div>
                    </div>
                    <div id="read_blank"></div>
                    <div id="read_card"><center>
                            <img src="../static/images/백꿈.png" class="card-img-top"style="width:225px;height:150px;"><br>
                            <div id="card_content">
                                <h10 class="card-title">title</h10><br>
                                <a class="card-text"style="font-size:15px;">설명글</a><br>
                                <a href="#" class="btn btn-primary"style="font-size:12px;">Go somewhere</a>
                            </div>
                    </div>
                </div>
            </h1>
        </div>
    </div>
    </body>
</html>

백엔드/instargram/frontend/templates/read1.html
<!DOCTYPE html>
{% load static %}
<html lang="ko">

    <head>
    <a href="#" onClick="window.open('../login1','_blank','toolbar=no,location=no,menubar=no,scrollbars=auto,resizable=no,directories=no,width=400,height=400,top=100,left=100')">로그인</a>
    <meta charset="UTF-8">
    <link href = "{% static 'css/homecss.css' %}" rel = "stylesheet">
    <title>Hagusa</title>
    </head>
    <body>
    <div id="m3">
        <div id ="read_title"><center>.....</div>
        <form>
            <input type="search" placeholder="Search" aria-label="Search" size ="30">
            <input type="submit"  value="" style="background-color:transparent;  border:0px transparent solid;"></button>
        </form>
        <div id="read_category">
            <br>
            <h1>
                <div id="read_blank1"></div>
                <div id="read_card"><center>
                    <img src="../static/images/백꿈.png" class="card-img-top"style="width:225px;height:150px;"><br>
                        <div id="card_content">
                            <h10 class="card-title">title</h10><br>
                            <a class="card-text"style="font-size:15px;">설명글</a><br>
                            <a href="#" class="btn btn-primary"style="font-size:12px;">Go somewhere</a>
                        </div>
                </div>
                <div id="read_blank"></div>
                <div id="read_card"><center>
                    <img src="../static/images/백꿈.png" class="card-img-top"style="width:225px;height:150px;"><br>
                        <div id="card_content">
                            <h10 class="card-title">title</h10><br>
                            <a class="card-text"style="font-size:15px;">설명글</a><br>
                            <a href="#" class="btn btn-primary"style="font-size:12px;">Go somewhere</a>
                        </div>
                </div>
                <div id="read_blank"></div>
                <div id="read_card"><center>
                    <img src="../static/images/백꿈.png" class="card-img-top"style="width:225px;height:150px;"><br>
                        <div id="card_content">
                            <h10 class="card-title">title</h10><br>
                            <a class="card-text"style="font-size:15px;">설명글</a><br>
                            <a href="#" class="btn btn-primary"style="font-size:12px;">Go somewhere</a>
                        </div>
                </div>
            </h1>
            <div id="read_jul"></div>
            <h1>
                <div id="read_center">
                    <div id="read_blank1"></div>
                    <div id="read_card"><center>
                    <img src="../static/images/백꿈.png" class="card-img-top"style="width:225px;height:150px;"><br>
                        <div id="card_content">
                            <h10 class="card-title">title</h10><br>
                            <a class="card-text"style="font-size:15px;">설명글</a><br>
                            <a href="#" class="btn btn-primary"style="font-size:12px;">Go somewhere</a>
                        </div>
                    </div>
                    <div id="read_blank"></div>
                    <div id="read_card"><center>
                    <img src="../static/images/백꿈.png" class="card-img-top"style="width:225px;height:150px;"><br>
                        <div id="card_content">
                            <h10 class="card-title">title</h10><br>
                            <a class="card-text"style="font-size:15px;">설명글</a><br>
                            <a href="#" class="btn btn-primary"style="font-size:12px;">Go somewhere</a>
                        </div>
                    </div>
                    <div id="read_blank"></div>
                    <div id="read_card"><center>
                    <img src="../static/images/백꿈.png" class="card-img-top"style="width:225px;height:150px;"><br>
                        <div id="card_content">
                            <h10 class="card-title">title</h10><br>
                            <a class="card-text"style="font-size:15px;">설명글</a><br>
                            <a href="#" class="btn btn-primary"style="font-size:12px;">Go somewhere</a>
                        </div>
                    </div>
                </div>
            </h1>
            <div id="read_jul"></div>
            <h1>
                <div id="read_below">
                    <div id="read_blank1"></div>
                    <div id="read_card"><center>
                    <img src="../static/images/백꿈.png" class="card-img-top"style="width:225px;height:150px;"><br>
                        <div id="card_content">
                            <h10 class="card-title">title</h10><br>
                            <a class="card-text"style="font-size:15px;">설명글</a><br>
                            <a href="#" class="btn btn-primary"style="font-size:12px;">Go somewhere</a>
                        </div>
                    </div>
                    <div id="read_blank"></div>
                    <div id="read_card"><center>
                    <img src="../static/images/백꿈.png" class="card-img-top"style="width:225px;height:150px;"><br>
                        <div id="card_content">
                            <h10 class="card-title">title</h10><br>
                            <a class="card-text"style="font-size:15px;">설명글</a><br>
                            <a href="#" class="btn btn-primary"style="font-size:12px;">Go somewhere</a>
                        </div>
                    </div>
                    <div id="read_blank"></div>
                    <div id="read_card"><center>
                    <img src="../static/images/백꿈.png" class="card-img-top"style="width:225px;height:150px;"><br>
                        <div id="card_content">
                            <h10 class="card-title">title</h10><br>
                            <a class="card-text"style="font-size:15px;">설명글</a><br>
                            <a href="#" class="btn btn-primary"style="font-size:12px;">Go somewhere</a>
                        </div>
                    </div>
                </div>
            </h1>
        </div>
    </div>
        <div id="header">
            <div>
                <ul class="nav">
                   
                </ul>
            </div> 
        </div>
    </body>
</html>